export enum RedisEnum {
  REDIS_SESSION = 'REDIS_SESSION',
  REDIS_REGISTER = 'REDIS_REGISTER',
  REDIS_PREVENT_DOS_ATT = 'REDIS_PREVENT_DOS_ATT',
  REDIS_TMP_FILE = 'REDIS_TMP_FILE',
  TOKEN_EXPIRE_TIME = 'TOKEN_EXPIRE_TIME',
}
